import time
import os
import io
import vertexai
from dotenv import load_dotenv
import uuid
from typing import Union, Dict, Any
from datetime import datetime
from google import genai
from google.genai import types
from google.adk.tools import ToolContext
import logging
import asyncio

# Load environment variables at module level
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

async def generate_image(prompt: str, image_name: str, tool_context: ToolContext = None, previous_image: str = None) -> Dict[str, Any]:
    """
    Generates an image and saves it to the 'images/' directory.
    If 'previous_image' is provided, it handles it via the LLM (editing is complex for Imagen-dedicated tools).
    Otherwise, it uses a dedicated Imagen model for high-fidelity generation.
    Args:
        prompt: The text prompt for the operation.
        image_name: The desired name for the output image file (without extension).
        tool_context: Optional ADK tool context for saving artifacts.
        previous_image: Optional path to an image to be edited.
    Returns:
        A dictionary with 'status', 'message', and 'artifact_name'.
    """
    project_id = os.environ.get("GOOGLE_CLOUD_PROJECT")
    location = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1")
    imagen_model = os.environ.get("IMAGEN_MODEL", "imagen-3.0-fast-generate-001")
    
    logger.info(f"Starting image generation for: {image_name}")
    logger.debug(f"Prompt: {prompt}")

    if not project_id:
        logger.error("GOOGLE_CLOUD_PROJECT environment variable is missing.")
        return {
            "status": "error",
            "message": "GOOGLE_CLOUD_PROJECT environment variable is not set.",
            "artifact_name": None
        }
    
    try:
        # Dedicated image models often work better in specific regions like us-central1
        client = genai.Client(vertexai=True, project=project_id, location=location)
        logger.info(f"Initialized GenAI client in {location} for project {project_id}")
    except Exception as e:
        logger.error(f"Failed to initialize genai.Client: {str(e)}")
        return {
            "status": "error",
            "message": f"Failed to initialize genai.Client: {str(e)}",
            "artifact_name": None
        }
    
    image_data = None
    
    try:
        if previous_image:
            # Editing with dedicated Imagen models uses a different workflow (inpainting/editing)
            logger.info(f"Editing existing image: {previous_image} with prompt '{prompt}'")
            # Use gemini-2.5-flash as per project mandate
            edit_model = "gemini-2.5-flash"
            
            with open(previous_image, "rb") as f:
                input_image_bytes = f.read()
                
            response = client.models.generate_content(
                model=edit_model,
                contents=[
                    types.Part.from_bytes(data=input_image_bytes, mime_type="image/png"),
                    prompt,
                ],
                config=types.GenerateContentConfig(
                    response_modalities=['IMAGE'],
                )
            )
            
            # Extract image data from the multimodal response
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    image_data = part.inline_data.data
                    logger.info("Successfully extracted image from Gemini multimodal response.")
                    break
        else:
            logger.info(f"Generating new image with model {imagen_model}")
            # Use dedicated image generation method
            response = client.models.generate_images(
                model=imagen_model,
                prompt=prompt,
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                    aspect_ratio="16:9",
                    safety_filter_level="block_low_and_above",
                    person_generation="allow_adult",
                ),
            )
            
            if response.generated_images:
                image_data = response.generated_images[0].image.image_bytes
                logger.info(f"Successfully generated new image with {imagen_model}")
            else:
                logger.warning(f"No image data was generated by {imagen_model}")
                return {
                    "status": "error",
                    "message": "No image data was generated by Imagen.",
                    "artifact_name": None
                }

        if not image_data:
            logger.error("No image data could be extracted.")
            return {
                "status": "error",
                "message": "No image data was extracted from the response.",
                "artifact_name": None
            }

        # Create the images directory if it doesn't exist
        output_dir = "images"
        os.makedirs(output_dir, exist_ok=True)

        # Determine the artifact name
        artifact_name = f"{image_name}.png"
        if tool_context:
            counter = str(tool_context.state.get("loop_iteration", 0))
            artifact_name = f"{image_name}_{counter}.png"
            report_artifact = types.Part.from_bytes(data=image_data, mime_type="image/png")
            await tool_context.save_artifact(artifact_name, report_artifact)
            logger.info(f"Saved artifact: {artifact_name} with index {counter}")

        # Save the image to file system
        file_path = os.path.join(output_dir, artifact_name)
        with open(file_path, "wb") as f:
            f.write(image_data)
            logger.info(f"Image written to file system: {file_path}")
        
        return {
            "status": "success",
            "message": f"Image generated and saved to {file_path}.",
            "artifact_name": artifact_name,
            "url": f"images/{artifact_name}"
        }

    except Exception as e:
        logger.exception(f"Unexpected error during image generation for {image_name}")
        return {
            "status": "error",
            "message": f"An unexpected error occurred during image generation: {str(e)}",
            "artifact_name": None
        }

